// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhzp69KlKGCu-qUrlxnPu-l-7S_LUyq7c',
    appId: '1:847304850303:web:2b885c9332a3b63890b84a',
    messagingSenderId: '847304850303',
    projectId: 'ecommerceapp-4edfd',
    authDomain: 'ecommerceapp-4edfd.firebaseapp.com',
    storageBucket: 'ecommerceapp-4edfd.appspot.com',
    measurementId: 'G-RJXNBBVSHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvEwpZMb0Flr2jiU2Uh-jTN3hkOAjmE-M',
    appId: '1:847304850303:android:20986d607bbe52fb90b84a',
    messagingSenderId: '847304850303',
    projectId: 'ecommerceapp-4edfd',
    storageBucket: 'ecommerceapp-4edfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOwPGwcGBE-YuN6T2v08oxJq4-LnI0aac',
    appId: '1:847304850303:ios:11323d2a2c5e2fc490b84a',
    messagingSenderId: '847304850303',
    projectId: 'ecommerceapp-4edfd',
    storageBucket: 'ecommerceapp-4edfd.appspot.com',
    iosClientId: '847304850303-sqc4ra04i26gskcrn5o1ju2k2snr9oak.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOwPGwcGBE-YuN6T2v08oxJq4-LnI0aac',
    appId: '1:847304850303:ios:67fcf356b258113990b84a',
    messagingSenderId: '847304850303',
    projectId: 'ecommerceapp-4edfd',
    storageBucket: 'ecommerceapp-4edfd.appspot.com',
    iosClientId: '847304850303-k2i6ib0q1ir8tjr2ap5k9v7gclms92rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
